name:                hoard
version:             0.1.0.0
synopsis:            TODO write a short description
description:         TODO write a long description
author:              Christian Georgii
maintainer:          christian.georgii@moduscreate.com
license:             MIT

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- bytestring
- cardano-api
- casing
- containers
- data-default
- directory
- effectful
- effectful-core
- effectful-th
- filepath
- hashable
- hasql
- hasql-pool
- hasql-transaction
- ki
- network-uri
- optparse-applicative
- rel8
- servant
- servant-server
- string-conversions
- text
- time
- unagi-chan
- unordered-containers
- uuid
- warp
- yaml

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: src

executables:
  hoard-exe:
    main:                Main.hs
    source-dirs:         app/hoard
    dependencies:
    - hoard

tests:
  hoard-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - hoard
    - hspec
    - QuickCheck
    - tasty
    - tasty-hspec
    - tasty-discover
    - servant-client
    - servant-client-core
    - http-client
    - wai
    - warp
    - process
    - directory
    - uuid
    - tmp-postgres
    - postgres-options
    - unix
