name:                hoard
version:             0.1.0.0
synopsis:            TODO write a short description
description:         TODO write a long description
author:              Christian Georgii
maintainer:          christian.georgii@moduscreate.com
license:             MIT

language: GHC2021

ghc-options:
- -Weverything
# SafeHaskell is a myth
- -Wno-unsafe
- -Wno-missing-safe-haskell-mode
# Removes all the pros of type inference
- -Wno-monomorphism-restriction
# Most of the time completely unnecessary
- -Wno-missing-kind-signatures
# Very tedious to enforce for _all_ local bindings
- -Wno-missing-local-signatures
# Tedious because it also enforces an explicit import list on records
- -Wno-missing-import-lists
# Noise
- -Wno-implicit-prelude
# Forces us to write ': instead of : for Effectful's (:) operator, and many
# other tedious things.
- -Wno-unticked-promoted-constructors
# False positive flags `base` and `tasty-discover`, unfortunately.
#
# `base` is used directly by the `Paths_hoard.hs` module generated by cabal, so
# we need to keep it as a dependency.
#
# `tasty-discover` is used in our testing harness to ease running test files
# through its compiler plugin. We don't use `tasty-discover` directly in our
# code though, so it is falsely flagged as unused.
- -Wno-unused-packages
- -O0
- -fplugin=Effectful.Plugin
- -threaded

dependencies:
- effectful-core
- effectful-plugin

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: src
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - atelier
    - aeson
    - base16-bytestring
    - base64-bytestring
    - data-default
    - time
    - bytestring
    - cardano-api
    - cardano-ledger-byron
    - cardano-ledger-core
    - casing
    - cborg
    - containers
    - contra-tracer
    - directory
    - effectful
    - effectful-th
    - filepath
    - hasql
    - hasql-pool
    - hasql-transaction
    - hs-opentelemetry-api
    - hs-opentelemetry-sdk
    - http-api-data
    - iproute
    - ki
    - list-t
    - network
    - network-mux
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-diffusion
    - ouroboros-consensus-protocol
    - resource-registry
    - stm
    - ouroboros-network
    - ouroboros-network-api
    - ouroboros-network-framework
    - ouroboros-network-protocols
    - prometheus-client
    - prometheus-metrics-ghc
    - rel8
    - servant-server
    - stm-containers
    - string-conversions
    - text
    - transformers
    - typed-process
    - typed-protocols
    - unagi-chan
    - unix
    - unordered-containers
    - uuid
    - warp
    - yaml

internal-libraries:
  hoard-prelude:
    source-dirs: prelude
    dependencies:
    - base
    - relude

  atelier:
    source-dirs: atelier/src
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - aeson
    - bytestring
    - casing
    - containers
    - contra-tracer
    - data-default
    - effectful
    - effectful-th
    - hasql
    - hasql-pool
    - hasql-transaction
    - hs-opentelemetry-api
    - hs-opentelemetry-exporter-otlp
    - hs-opentelemetry-sdk
    - http-api-data
    - ki
    - list-t
    - prometheus-client
    - prometheus-metrics-ghc
    - stm-containers
    - text
    - time
    - time-units
    - unagi-chan
    - unordered-containers
    - uuid

  atelier-testing:
    source-dirs: atelier/testing
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - atelier
    - hasql
    - hasql-pool
    - hspec
    - postgres-options
    - string-conversions
    - text
    - tmp-postgres
    - unix
    - uuid

executables:
  hoard-exe:
    main:                Main.hs
    source-dirs:         app/hoard
    ghc-options:
    - '"-with-rtsopts=-N -T"'
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - hoard
    - atelier
    - data-default
    - effectful

tests:
  atelier-test:
    main:                Driver.hs
    source-dirs:         atelier/test
    ghc-options:
    # Complains about `test/Driver.hs` emitted by tasty-discover, and is handled by
    # our fourmolu config.
    - -Wno-prepositive-qualified-module 
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - atelier
    - async
    - containers
    - effectful
    - hs-opentelemetry-api
    - hedgehog
    - hspec
    - hspec-hedgehog
    - stm
    - tasty
    - tasty-hspec
    - time

  hoard-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    # Complains about `test/Driver.hs` emitted by tasty-discover, and is handled by
    # our fourmolu config.
    - -Wno-prepositive-qualified-module 
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - hoard
    - atelier
    - atelier-testing
    - "ouroboros-consensus-cardano:unstable-byron-testlib"
    - "ouroboros-consensus-cardano:unstable-shelley-testlib"
    - "ouroboros-consensus:unstable-consensus-testlib"
    - aeson
    - async
    - cardano-api
    - cardano-ledger-core
    - data-default
    - effectful
    - hasql
    - hasql-pool
    - hasql-transaction
    - hs-opentelemetry-api
    - hspec
    - http-client
    - network
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-protocol
    - ouroboros-network-api
    - ouroboros-network-protocols
    - process
    - rel8
    - servant-client
    - servant-client-core
    - servant-server
    - string-conversions
    - tasty
    - tasty-discover
    - tasty-hspec
    - text
    - time
    - transformers
    - uuid
    - warp
