name:                hoard
version:             0.1.0.0
synopsis:            TODO write a short description
description:         TODO write a long description
author:              Christian Georgii
maintainer:          christian.georgii@moduscreate.com
license:             MIT

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O0
- -fplugin=Effectful.Plugin
- -threaded

dependencies:
- effectful-core
- effectful-plugin

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: src
  dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - aeson
    - async
    - base16-bytestring
    - data-default
    - time
    - bytestring
    - cardano-api
    - cardano-ledger-core
    - cardano-ledger-shelley
    - casing
    - cborg
    - containers
    - contra-tracer
    - directory
    - effectful
    - effectful-th
    - filepath
    - hashable
    - hasql
    - hasql-pool
    - hasql-transaction
    - hs-opentelemetry-api
    - hs-opentelemetry-exporter-otlp
    - hs-opentelemetry-sdk
    - http-client
    - http-client-tls
    - http-types
    - iproute
    - ki
    - list-t
    - network
    - network-mux
    - network-uri
    - optparse-applicative
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-consensus-diffusion
    - ouroboros-consensus-protocol
    - ouroboros-network
    - ouroboros-network-api
    - ouroboros-network-framework
    - ouroboros-network-protocols
    - prometheus-client
    - prometheus-metrics-ghc
    - rel8
    - serialise
    - servant
    - servant-server
    - stm-containers
    - string-conversions
    - text
    - transformers
    - typed-process
    - typed-protocols
    - unagi-chan
    - unix
    - unordered-containers
    - uuid
    - warp
    - yaml

internal-libraries:
  hoard-prelude:
    source-dirs: prelude
    dependencies:
    - base
    - relude
    - effectful

executables:
  hoard-exe:
    main:                Main.hs
    source-dirs:         app/hoard
    ghc-options:
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - hoard
    - data-default
    - effectful

tests:
  hoard-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - name: base
      mixin:
        - hiding (Prelude)
    - hoard-prelude
    - hoard
    - "ouroboros-consensus-cardano:unstable-byron-testlib"
    - "ouroboros-consensus-cardano:unstable-shelley-testlib"
    - "ouroboros-consensus:unstable-consensus-testlib"
    - QuickCheck
    - async
    - cardano-api
    - data-default
    - directory
    - effectful
    - hasql
    - hasql-pool
    - hasql-transaction
    - hspec
    - http-client
    - network
    - ouroboros-consensus
    - ouroboros-consensus-cardano
    - ouroboros-network-api
    - postgres-options
    - process
    - rel8
    - servant-client
    - servant-client-core
    - servant-server
    - string-conversions
    - tasty
    - tasty-discover
    - tasty-hspec
    - text
    - time
    - tmp-postgres
    - transformers
    - unix
    - uuid
    - wai
    - warp
