name:                hoard
version:             0.1.0.0
synopsis:            TODO write a short description
description:         TODO write a long description
author:              Christian Georgii
maintainer:          christian.georgii@moduscreate.com
license:             MIT

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O0
- -fplugin=Effectful.Plugin
- -threaded

dependencies:
- name: base
  mixin:
    - hiding (Prelude)
- name: relude
  mixin:
    - (Relude as Prelude)
    - '' # Required to make the rest of relude importable
- aeson
- async
- base16-bytestring
- bytestring
- cardano-api
- cborg
- contra-tracer
- ouroboros-network
- ouroboros-network-api
- ouroboros-network-protocols
- ouroboros-network-framework
- ouroboros-consensus
- ouroboros-consensus-cardano
- ouroboros-consensus-diffusion
- ouroboros-consensus-protocol
- cardano-ledger-core
- cardano-ledger-shelley
- network-mux
- typed-protocols
- casing
- containers
- data-default
- directory
- effectful
- effectful-core
- effectful-plugin
- effectful-th
- filepath
- hashable
- hasql
- hasql-pool
- hasql-transaction
- iproute
- ki
- network
- network-uri
- optparse-applicative
- prometheus-client
- prometheus-metrics-ghc
- hs-opentelemetry-api
- hs-opentelemetry-exporter-otlp
- hs-opentelemetry-sdk
- http-client
- http-client-tls
- http-types
- rel8
- serialise
- servant
- servant-server
- string-conversions
- text
- time
- transformers
- unagi-chan
- unordered-containers
- uuid
- warp
- yaml
- typed-process
- unix

default-extensions:
- BlockArguments
- DataKinds
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FlexibleContexts
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- StrictData
- TemplateHaskell
- TypeFamilies

library:
  source-dirs: src

executables:
  hoard-exe:
    main:                Main.hs
    source-dirs:         app/hoard
    ghc-options:
    - -with-rtsopts=-N
    - -with-rtsopts=-T
    dependencies:
    - hoard

tests:
  hoard-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - hoard
    - hspec
    - QuickCheck
    - tasty
    - tasty-hspec
    - tasty-discover
    - servant-client
    - servant-client-core
    - "ouroboros-consensus:unstable-consensus-testlib"
    - "ouroboros-consensus-cardano:unstable-shelley-testlib"
    - "ouroboros-consensus-cardano:unstable-byron-testlib"
    - http-client
    - wai
    - warp
    - process
    - directory
    - uuid
    - tmp-postgres
    - postgres-options
    - unix
