{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.10";
      identifier = { name = "casing"; version = "0.1.4.1"; };
      license = "MIT";
      copyright = "";
      maintainer = "tdammers@gmail.com";
      author = "Tobias Dammers";
      homepage = "";
      url = "";
      synopsis = "Convert between various source code casing conventions";
      description = "Converts between camelCase, PascalCase, kebab-case, and three\nflavors of snake_case.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."split" or (errorHandler.buildDepError "split"))
        ];
        buildable = true;
      };
      tests = {
        "tests" = {
          depends = [
            (hsPkgs."base" or (errorHandler.buildDepError "base"))
            (hsPkgs."casing" or (errorHandler.buildDepError "casing"))
            (hsPkgs."tasty" or (errorHandler.buildDepError "tasty"))
            (hsPkgs."tasty-hunit" or (errorHandler.buildDepError "tasty-hunit"))
          ];
          buildable = true;
        };
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/casing-0.1.4.1.tar.gz";
      sha256 = "106271c00246b551f2ef6a2e511437c9f0e1f3bb920a283f6f9eaa0940b4f8ca";
    });
  }) // {
    package-description-override = "-- Initial casing.cabal generated by cabal init. For further \r\n-- documentation, see http://haskell.org/cabal/users-guide/\r\n\r\nname: casing\r\nversion: 0.1.4.1\r\nx-revision: 1\r\nsynopsis: Convert between various source code casing conventions\r\ndescription: Converts between camelCase, PascalCase, kebab-case, and three\r\n             flavors of snake_case.\r\nlicense: MIT\r\nlicense-file: LICENSE\r\nauthor: Tobias Dammers\r\nmaintainer: tdammers@gmail.com\r\n-- copyright: \r\ncategory: Text\r\nbuild-type: Simple\r\n-- extra-source-files: \r\ncabal-version: >=1.10\r\n\r\nsource-repository head\r\n    type: git\r\n    location: https://github.com/tdammers/casing\r\n\r\nlibrary\r\n  exposed-modules: Text.Casing\r\n  -- other-modules: \r\n  -- other-extensions: \r\n  build-depends: base >=4.8 && <5\r\n               , split\r\n  hs-source-dirs: src\r\n  default-language: Haskell2010\r\n\r\ntest-suite tests\r\n  main-is: Spec.hs\r\n  hs-source-dirs: tests\r\n  type: exitcode-stdio-1.0\r\n  default-language: Haskell2010\r\n  build-depends: base >=4.8 && <5\r\n               , casing\r\n               , tasty\r\n               , tasty-hunit\r\n";
  }