{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.22";
      identifier = { name = "proto-lens-runtime"; version = "0.7.0.7"; };
      license = "BSD-3-Clause";
      copyright = "Google Inc.";
      maintainer = "proto-lens@googlegroups.com";
      author = "Judah Jacobson";
      homepage = "https://github.com/google/proto-lens#readme";
      url = "";
      synopsis = "";
      description = "Modules that are needed by the Haskell files generated by proto-lens-protoc. For forwards compatibility, we reexport them as new module names so that other packages don't accidentally write non-generated code that relies on these modules being reexported by this package.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."deepseq" or (errorHandler.buildDepError "deepseq"))
          (hsPkgs."filepath" or (errorHandler.buildDepError "filepath"))
          (hsPkgs."lens-family" or (errorHandler.buildDepError "lens-family"))
          (hsPkgs."proto-lens" or (errorHandler.buildDepError "proto-lens"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
          (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
        ];
        buildable = true;
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/proto-lens-runtime-0.7.0.7.tar.gz";
      sha256 = "d0f6e91dc81f88c6ba1be683bb6b85d817b175671f0abe600f1015e7f5bbed25";
    });
  }) // {
    package-description-override = "cabal-version: 1.22\r\n\r\n-- This file has been generated from package.yaml by hpack version 0.37.0.\r\n--\r\n-- see: https://github.com/sol/hpack\r\n\r\nname:           proto-lens-runtime\r\nversion:        0.7.0.7\r\nx-revision: 1\r\ndescription:    Modules that are needed by the Haskell files generated by proto-lens-protoc. For forwards compatibility, we reexport them as new module names so that other packages don't accidentally write non-generated code that relies on these modules being reexported by this package.\r\nhomepage:       https://github.com/google/proto-lens#readme\r\nbug-reports:    https://github.com/google/proto-lens/issues\r\nauthor:         Judah Jacobson\r\nmaintainer:     proto-lens@googlegroups.com\r\ncopyright:      Google Inc.\r\nlicense:        BSD3\r\nlicense-file:   LICENSE\r\nbuild-type:     Simple\r\nextra-source-files:\r\n    Changelog.md\r\n\r\nsource-repository head\r\n  type: git\r\n  location: https://github.com/google/proto-lens\r\n  subdir: proto-lens-runtime\r\n\r\nlibrary\r\n  other-modules:\r\n      Paths_proto_lens_runtime\r\n  reexported-modules:\r\n      Prelude as Data.ProtoLens.Runtime.Prelude\r\n    , Control.DeepSeq as Data.ProtoLens.Runtime.Control.DeepSeq\r\n    , Data.Int as Data.ProtoLens.Runtime.Data.Int\r\n    , Data.Monoid as Data.ProtoLens.Runtime.Data.Monoid\r\n    , Data.Word as Data.ProtoLens.Runtime.Data.Word\r\n    , Data.ByteString as Data.ProtoLens.Runtime.Data.ByteString\r\n    , Data.ByteString.Char8 as Data.ProtoLens.Runtime.Data.ByteString.Char8\r\n    , Data.Map as Data.ProtoLens.Runtime.Data.Map\r\n    , Data.ProtoLens as Data.ProtoLens.Runtime.Data.ProtoLens\r\n    , Data.ProtoLens.Encoding.Bytes as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Bytes\r\n    , Data.ProtoLens.Encoding.Growing as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Growing\r\n    , Data.ProtoLens.Encoding.Parser.Unsafe as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Parser.Unsafe\r\n    , Data.ProtoLens.Field as Data.ProtoLens.Runtime.Data.ProtoLens.Field\r\n    , Data.ProtoLens.Prism as Data.ProtoLens.Runtime.Data.ProtoLens.Prism\r\n    , Data.ProtoLens.Encoding.Wire as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Wire\r\n    , Data.ProtoLens.Service.Types as Data.ProtoLens.Runtime.Data.ProtoLens.Service.Types\r\n    , Data.ProtoLens.Message.Enum as Data.ProtoLens.Runtime.Data.ProtoLens.Message.Enum\r\n    , Data.Text as Data.ProtoLens.Runtime.Data.Text\r\n    , Data.Text.Encoding as Data.ProtoLens.Runtime.Data.Text.Encoding\r\n    , Data.Vector as Data.ProtoLens.Runtime.Data.Vector\r\n    , Data.Vector.Generic as Data.ProtoLens.Runtime.Data.Vector.Generic\r\n    , Data.Vector.Unboxed as Data.ProtoLens.Runtime.Data.Vector.Unboxed\r\n    , Lens.Family2 as Data.ProtoLens.Runtime.Lens.Family2\r\n    , Lens.Family2.Unchecked as Data.ProtoLens.Runtime.Lens.Family2.Unchecked\r\n    , Text.Read as Data.ProtoLens.Runtime.Text.Read\r\n  build-depends:\r\n      base >=4.10 && <4.23\r\n    , bytestring >=0.10 && <0.13\r\n    , containers >=0.5 && <0.9\r\n    , deepseq >=1.4 && <1.6\r\n    , filepath >=1.4 && <1.6\r\n    , lens-family >=1.2 && <2.2\r\n    , proto-lens ==0.7.*\r\n    , text >=1.2 && <2.2\r\n    , vector >=0.11 && <0.14\r\n  default-language: Haskell2010\r\n";
  }