{ system
  , compiler
  , flags
  , pkgs
  , hsPkgs
  , pkgconfPkgs
  , errorHandler
  , config
  , ... }:
  ({
    flags = {};
    package = {
      specVersion = "1.22";
      identifier = { name = "proto-lens-runtime"; version = "0.7.0.7"; };
      license = "BSD-3-Clause";
      copyright = "Google Inc.";
      maintainer = "proto-lens@googlegroups.com";
      author = "Judah Jacobson";
      homepage = "https://github.com/google/proto-lens#readme";
      url = "";
      synopsis = "";
      description = "Modules that are needed by the Haskell files generated by proto-lens-protoc. For forwards compatibility, we reexport them as new module names so that other packages don't accidentally write non-generated code that relies on these modules being reexported by this package.";
      buildType = "Simple";
    };
    components = {
      "library" = {
        depends = [
          (hsPkgs."base" or (errorHandler.buildDepError "base"))
          (hsPkgs."bytestring" or (errorHandler.buildDepError "bytestring"))
          (hsPkgs."containers" or (errorHandler.buildDepError "containers"))
          (hsPkgs."deepseq" or (errorHandler.buildDepError "deepseq"))
          (hsPkgs."filepath" or (errorHandler.buildDepError "filepath"))
          (hsPkgs."lens-family" or (errorHandler.buildDepError "lens-family"))
          (hsPkgs."proto-lens" or (errorHandler.buildDepError "proto-lens"))
          (hsPkgs."text" or (errorHandler.buildDepError "text"))
          (hsPkgs."vector" or (errorHandler.buildDepError "vector"))
        ];
        buildable = true;
      };
    };
  } // {
    src = pkgs.lib.mkDefault (pkgs.fetchurl {
      url = "http://hackage.haskell.org/package/proto-lens-runtime-0.7.0.7.tar.gz";
      sha256 = "d0f6e91dc81f88c6ba1be683bb6b85d817b175671f0abe600f1015e7f5bbed25";
    });
  }) // {
    package-description-override = "cabal-version: 1.22\n\n-- This file has been generated from package.yaml by hpack version 0.37.0.\n--\n-- see: https://github.com/sol/hpack\n\nname:           proto-lens-runtime\nversion:        0.7.0.7\ndescription:    Modules that are needed by the Haskell files generated by proto-lens-protoc. For forwards compatibility, we reexport them as new module names so that other packages don't accidentally write non-generated code that relies on these modules being reexported by this package.\nhomepage:       https://github.com/google/proto-lens#readme\nbug-reports:    https://github.com/google/proto-lens/issues\nauthor:         Judah Jacobson\nmaintainer:     proto-lens@googlegroups.com\ncopyright:      Google Inc.\nlicense:        BSD3\nlicense-file:   LICENSE\nbuild-type:     Simple\nextra-source-files:\n    Changelog.md\n\nsource-repository head\n  type: git\n  location: https://github.com/google/proto-lens\n  subdir: proto-lens-runtime\n\nlibrary\n  other-modules:\n      Paths_proto_lens_runtime\n  reexported-modules:\n      Prelude as Data.ProtoLens.Runtime.Prelude\n    , Control.DeepSeq as Data.ProtoLens.Runtime.Control.DeepSeq\n    , Data.Int as Data.ProtoLens.Runtime.Data.Int\n    , Data.Monoid as Data.ProtoLens.Runtime.Data.Monoid\n    , Data.Word as Data.ProtoLens.Runtime.Data.Word\n    , Data.ByteString as Data.ProtoLens.Runtime.Data.ByteString\n    , Data.ByteString.Char8 as Data.ProtoLens.Runtime.Data.ByteString.Char8\n    , Data.Map as Data.ProtoLens.Runtime.Data.Map\n    , Data.ProtoLens as Data.ProtoLens.Runtime.Data.ProtoLens\n    , Data.ProtoLens.Encoding.Bytes as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Bytes\n    , Data.ProtoLens.Encoding.Growing as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Growing\n    , Data.ProtoLens.Encoding.Parser.Unsafe as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Parser.Unsafe\n    , Data.ProtoLens.Field as Data.ProtoLens.Runtime.Data.ProtoLens.Field\n    , Data.ProtoLens.Prism as Data.ProtoLens.Runtime.Data.ProtoLens.Prism\n    , Data.ProtoLens.Encoding.Wire as Data.ProtoLens.Runtime.Data.ProtoLens.Encoding.Wire\n    , Data.ProtoLens.Service.Types as Data.ProtoLens.Runtime.Data.ProtoLens.Service.Types\n    , Data.ProtoLens.Message.Enum as Data.ProtoLens.Runtime.Data.ProtoLens.Message.Enum\n    , Data.Text as Data.ProtoLens.Runtime.Data.Text\n    , Data.Text.Encoding as Data.ProtoLens.Runtime.Data.Text.Encoding\n    , Data.Vector as Data.ProtoLens.Runtime.Data.Vector\n    , Data.Vector.Generic as Data.ProtoLens.Runtime.Data.Vector.Generic\n    , Data.Vector.Unboxed as Data.ProtoLens.Runtime.Data.Vector.Unboxed\n    , Lens.Family2 as Data.ProtoLens.Runtime.Lens.Family2\n    , Lens.Family2.Unchecked as Data.ProtoLens.Runtime.Lens.Family2.Unchecked\n    , Text.Read as Data.ProtoLens.Runtime.Text.Read\n  build-depends:\n      base >=4.10 && <4.21\n    , bytestring >=0.10 && <0.13\n    , containers >=0.5 && <0.8\n    , deepseq >=1.4 && <1.6\n    , filepath >=1.4 && <1.6\n    , lens-family >=1.2 && <2.2\n    , proto-lens ==0.7.*\n    , text >=1.2 && <2.2\n    , vector >=0.11 && <0.14\n  default-language: Haskell2010\n";
  }