# Development environment secrets
# After editing, encrypt this file with: nix run .#secrets-edit dev
database:
  users:
    reader:
      user: hoard_reader
      password: ""  # TODO: Set reader password
    writer:
      user: hoard_writer
      password: ""  # TODO: Set writer password
