#ENC[AES256_GCM,data:0sdgV/zbSDkupKLqk8pNbaTatLu6U9IPXA2K5KIfag==,iv:aSm1HXaej/qHqAcmSYk0P0w0g/boOfVr2uwqd4Zrvm4=,tag:Ze5ylasJc5R8k8IRbCBAAQ==,type:comment]
#ENC[AES256_GCM,data:c6IEm0OZ9OiZdqWwfVjB8rVZoIDUagIHckA4ZwyaY8TFNyA0poOGIrjT2obkxc09CKB0DTJq3FSUPOz8gT30sn7MyA==,iv:J7nlb9UtWhjwpS/AEvpDLsQTJs8dZqPgx+UTvTYCQgk=,tag:HHif3WV9y5WYaVB4zmtHKQ==,type:comment]
database:
    users:
        reader:
            user: ENC[AES256_GCM,data:18UJxE2Svx9QABn4,iv:yhkdzsOnDrmQJuCPrDvaV53y3+XC3uUKF21sgqQP3U4=,tag:1Pqo5p6hWiuWsbl2yqUH+Q==,type:str]
            #ENC[AES256_GCM,data:8LSmSRLZ2x+ZQYWXYUT0xIoBZKv1JMuzSGg=,iv:wZrgxuH1GqT3CZGTo9RjtcbQ/CzGwyJBtvJU8RilWUY=,tag:vVlwPc9hd/QXUBrwssLmag==,type:comment]
            password: ""
        writer:
            user: ENC[AES256_GCM,data:TAn8JARtgi4pE+RO,iv:ALwWzF/0S+672Dpp86PUOgygLZz0oxbNdZ/o9v3KoRI=,tag:5AbRykWvVoMbFoau5cMJvg==,type:str]
            #ENC[AES256_GCM,data:2rj2kRXFSVIvMtoIj+EstSL82hIwoB0wzro=,iv:B2kM7GQdrmUfT8XeS21NPub6jmiIa+aqPntAX7SajqY=,tag:7FunK/easPo5YhSJB3P7WA==,type:comment]
            password: ""
sops:
    age:
        - recipient: age1kq67lkr7sz9q0qk4k4nf7rdn88mzkscpersvhgf500gpke9wfcjqkxzm69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacVg5V3VpTzdGTngzQmNu
            dmtJZEpuYSt4RXloeWNBa3A2N0ltMkxvVjE0CkxnOVFkdDFnT0w1eWtJZGovL1NT
            N2VPN2pPWVEyUS9ZcXRiNXQ2M2w1TGMKLS0tIDArT3ZuZkhneFM1Q0Q1ZitrUSs0
            TE9FYm5aNFRhSkU5L1lwTGpVS1JrNW8KmcT2/bQ8sZKVZ1khohrFLFlfl3VhKWq/
            vLZ6J2Rec0ThPiPMMnEYVA68f54ZZMEEc+18bQWro2rfboKa9VRwRQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1444057eh6n48vd4ncz4lr8mvz5yaqah20a3nngngee4hfl25u4hqm5f69f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMY0lqWlNQb203cTNScWNS
            SmxDRzhDNk1sTWtaVjJ4bWRlMS9SMm5VakRJCm5qRzVPbUZOcnRQWlBEZjA5Wnps
            ajBpZE15L0IrN25rWXd1bC9seis1S2MKLS0tIEduSUxBTmtjR1ZHZUdiRTlUWWdT
            ZE9DaXgzbTZoSFdwc0hLUll5d2piYWcKy2KrB7vW4AZazV404yQckdXG3HL075fw
            7CB3H5hO2pGt+FPzyrMuiNx6pgQS4qoBTyoY2pDpGsRFj9F15824hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pzemcrww7x0azxvyvavd92r9a585xr5yep5lssfyh3qd5hyvjgqqmuq3ne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdldXYURLQUZkRWJhZ0dL
            RUFha1YvOVprWE1RTkNXY0h6dWZNdzNyUG5jCmtoMjJmOVJTVFJyb2pmUElXcFBj
            U2ZnUVBVRmlSUmVLNmxDSEpyUzVMd1kKLS0tIDRoSjc1WXFhdksyRmlMblhlMFZw
            YjZPQms2R2QvTVUyQTI0dVZxYVF1ZGcKTpfn10qRhZqSvlttkRNASxrGk/HBPmgQ
            JUFKHCjcqlzSEMVtJopFO2myi6XpaWuE/fUgrlHx7KsGGUnSUoNGYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T13:14:23Z"
    mac: ENC[AES256_GCM,data:ZPJClToUJqVxXL6A823diz4s1udEUPAJE+8+dJv/BOV+fPRFqIAdY2prs1pZdYtvtkEJ+mnXh3CdVrO+ZRkUNf8L5n2jtWrk9Ca3Wd3442d0JSsDTeFB3aZxuwh4K3BksuZXr5qFTTiW85GciHRQnGZHqzW/VOgLySOQ9wWnjO8=,iv:tBxH1sQkZtmvlltCW2vybiRfZV4ITsxJrRImX2CxVn8=,tag:rH1UhRUR9o0cRanoI0Obxw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
