#ENC[AES256_GCM,data:QlxkIgB3YvIV1Oq7VdyADi9xPoh2PIKV50+8xQ==,iv:h9V7HAun7eITMOWlgfkWXdswdbvwgK5LudIIOOUE4kk=,tag:ZZ4B1kUg2/SOGvX9sICJDg==,type:comment]
#ENC[AES256_GCM,data:1ifc+DPXuAv+gNSoYUs2GlVFsjLVFVakR72ShO2qB1PPDNJMlLJtJ9VPmCssV1PqTiBlWseTMpeuYBsNs+IKpUcRfphHOQ==,iv:KgMHUTZluCcDG3kGAVzWPrVLjEeJdVXB4/VwyKudJdM=,tag:AU82rZVRbWl2VdIj3FvfTQ==,type:comment]
database:
    users:
        reader:
            user: ENC[AES256_GCM,data:N/HZPyYj4zRYoJqi,iv:Y5wI9FHlmhX8DbKE0Sr2/SC/FcOxqTmZDR91JDtd92Y=,tag:fduzOXOGivY8QGoWr2Bemg==,type:str]
            #ENC[AES256_GCM,data:Y3VvsjtM1CmlwIgkRZPJMp2Tgi3lnyR8XcY=,iv:q+8lCV9x3tRQgMD4l0z/nZuktKva4qcy7vlkpdIu2t8=,tag:sIsKfn967IuROXy3gymmbg==,type:comment]
            password: ""
        writer:
            user: ENC[AES256_GCM,data:7f6i/r/Nu+Vmqs9I,iv:rA2AD9ktQj4uBHRvfq9JMThZX7xOGtOXadHH/PQ8fc8=,tag:TYmyly1IYaGkTRtqdZChnw==,type:str]
            #ENC[AES256_GCM,data:hTfDqhKqw3KyZYcAObg5GDfBOe3PcBQlrjo=,iv:ktEXJm7JcFloG+R/+sZjpV0gKGqvge9rV5UGP8cx5DM=,tag:HmMQzRqtfmN1VEOec4iUQQ==,type:comment]
            password: ""
sops:
    age:
        - recipient: age1kq67lkr7sz9q0qk4k4nf7rdn88mzkscpersvhgf500gpke9wfcjqkxzm69
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NmRQaDJjcXRGS01DdmtN
            L2ZJd0o2Wk1VRUxLYURnN3dpamVwNTdBbXlBCmJvYWQzMzE3YURnQkxKWmRqTGhD
            aWJ1ZUN4djkvMFdMYjR0Qk5FZU5paE0KLS0tIDdzZkFFUG94T1BacG5BOWJQZnJS
            TElvNllDZUg2WVY5V0tSWlNCY3czaTQKiMQErduONPu1ZiT8XwBxp2YNUgHiZ/+/
            FtFgy0BntiIlzSMCNaz6eEgtP6OWUk0CXG5SjtAzO5pUCeZUi3jA4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1444057eh6n48vd4ncz4lr8mvz5yaqah20a3nngngee4hfl25u4hqm5f69f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NzU0SHl6MUVucWQwMWU1
            R090b2FONUgrWThtN204cHFpWGNZdjcyZ2hjCjJidVhzT3dBdlRzdkxuTDZaL1pX
            bzlHRERXZzV6YlhROVNiVW1VeHZYcXMKLS0tIG5uV09YYUEzOUdkMGtrMHdBZFJG
            NkFoTWNWbGFrNDQrbDJPZGttYVltQ3cKeiDRBFBicdUiRIfNmXfxokKEAXtTjDjh
            qMu2MErXSe5hAKUJgu6frl6VLvzK89/B8TSF90DoAcKvNJf0Bzlo0A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pzemcrww7x0azxvyvavd92r9a585xr5yep5lssfyh3qd5hyvjgqqmuq3ne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNEdCaFdqV01VdyswcDlz
            ZWJMcXNDQ3YzTUloYllVS2lRYjlWR3hJcGo4CjFuZTU2eFZTNVk1R1BXOWRPRTVF
            b2RJVGw4N3NIMDhxNWkvUkFkOVNNalEKLS0tIGN0emRlRFpPbHlySWRJNWNqNHJD
            OHZXUDM4S200aWx2Znl5RkdBbGFIZkEK+cwPy7TSttTtDlFEnTuVXIzZR+wTRPZT
            B7jCm1Z5IRyz3GGCN5Fd3AwXhLR3gYykYl0HfAtm5HNCusz5+vdkkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-27T13:14:25Z"
    mac: ENC[AES256_GCM,data:LpdE9FVRK2zlBJOR0Rc1IGuK1JVi+IX6GogWiyVvNcRnITvvfvlJz2hPk3cuxyZ1B6GfamEVWzrGMgZgKdHypg/pxm1g6lxD5K14ExqLWxvj0jv3y/zEDee/tbbz8ZmO0BMfxEPnVK6xC++fhPgiVVd1KoIHBwlTCNtauEUCrcE=,iv:kNVAf0AoX4PCk6m30fXOWkHXFEe1dYsmy8hZ2YMSoFc=,tag:hY0HWKguYfPy6uMoug/VYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
